/*
 * @(#)AlignToolBar.java  1.2  2008-05-23
 *
 * Copyright (c) 2007-2008 by the original authors of JHotDraw
 * and all its contributors.
 * All rights reserved.
 *
 * The copyright of this software is owned by the authors and  
 * contributors of the JHotDraw project ("the copyright holders").  
 * You may not use, copy or modify this software, except in  
 * accordance with the license agreement you entered into with  
 * the copyright holders. For details see accompanying license terms. 
 */
package org.jhotdraw.samples.svg.gui;

import dk.sdu.mmmi.featuretracer.lib.FeatureEntryPoint;
import javax.swing.border.*;
import org.jhotdraw.util.*;

import java.awt.*;
import javax.swing.*;
import org.jhotdraw.app.JHotDrawFeatures;
import org.jhotdraw.draw.*;
import org.jhotdraw.draw.action.*;
import org.jhotdraw.gui.plaf.palette.*;

/**
 * AlignToolBar.
 *
 * @author Werner Randelshofer
 * @version 1.2 2008-05-23 Hide the toolbar if nothing is selected, and no
 * creation tool is active. 
 * <br>1.1 2008-03-26 Don't draw button borders. 
 * <br>1.0 May 1, 2007 Created.
 */
public class AlignToolBar extends AbstractToolBar {

    private SelectionComponentDisplayer displayer;
    ResourceBundleUtil labels = ResourceBundleUtil.getBundle("org.jhotdraw.samples.svg.Labels");
    JPanel p = new JPanel();

    /** Creates new instance. */
    public AlignToolBar() {
        setName(labels.getString(getID() + ".toolbar"));
    }
    public JPanel getJPanel(){
        return p;
    }

    @Override
    public void setEditor(DrawingEditor newValue) {
        DrawingEditor oldValue = getEditor();
        if (displayer != null) {
            displayer.dispose();
            displayer = null;
        }
        super.setEditor(newValue);
        if (newValue != null) {
            displayer = new SelectionComponentDisplayer(editor, this);
            displayer.setMinSelectionCount(2);
            displayer.setVisibleIfCreationTool(false);
        }
    }
    
    public void createBtn (AbstractButton btn){
        btn.setUI((PaletteButtonUI) PaletteButtonUI.createUI(btn));
        btn.putClientProperty("hideActionText", Boolean.TRUE);
        btn.setText(null);
    }
    
    public void createBorder(){
        p.setBorder(new EmptyBorder(5, 5, 5, 8));
    }
    
    public void createBtnEast (JPanel p, GridBagConstraints gbc){
        
        AbstractButton btn;
        
        gbc.insets = new Insets(0, 3, 0, 0);
        btn = new JButton(new AlignAction.East(editor, labels));
        createBtn(btn);
        p.add(btn, gbc);
    }
    
        public void createBtnWest (JPanel p, GridBagConstraints gbc){
        AbstractButton btn;
        
        gbc.gridy = 0;
        gbc.insets = new Insets(0, 3, 0, 0);
        btn = new JButton(new AlignAction.West(editor, labels));
        createBtn(btn);
        p.add(btn, gbc);
    }
        
        public void createBtnNorth (JPanel p, GridBagConstraints gbc){
        AbstractButton btn;
        
        gbc.gridy = 1;
        gbc.insets = new Insets(3, 0, 0, 0);
        btn = new JButton(new AlignAction.North(editor, labels));
        createBtn(btn);
        p.add(btn, gbc);
    }
        
        public void createBtnSouth (JPanel p, GridBagConstraints gbc){
        AbstractButton btn;
        
        gbc.insets = new Insets(3, 3, 0, 0);
        btn = new JButton(new AlignAction.South(editor, labels));
        createBtn(btn);
        p.add(btn, gbc);
    }
        
        public void createBtnHori (JPanel p, GridBagConstraints gbc){
        AbstractButton btn;
        
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.insets = new Insets(3, 0, 0, 0);
        btn = new JButton(new AlignAction.Horizontal(editor, labels));
        createBtn(btn);
        p.add(btn, gbc);
    }
        
        public void createBtnVerti (JPanel p, GridBagConstraints gbc){
        AbstractButton btn;
        
        gbc.gridx = 1;
        gbc.insets = new Insets(3, 3, 0, 0);
        btn = new JButton(new AlignAction.Vertical(editor, labels));
        createBtn(btn);
        p.add(btn, gbc);
    }

    @Override
    @FeatureEntryPoint(JHotDrawFeatures.ALIGN_PALETTE)
    protected JComponent createDisclosedComponent(int state) {
        createBorder();
        GridBagLayout layout = new GridBagLayout();
        p.setLayout(layout);
        p.setOpaque(false);

        GridBagConstraints gbc = new GridBagConstraints();
        
        createBtnWest(p,gbc);
        createBtnEast(p,gbc);
        createBtnNorth(p,gbc);
        createBtnSouth(p,gbc);
        createBtnHori(p,gbc);
        createBtnVerti(p,gbc);
        return p;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected String getID() {
        return "align";
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
