/*
 * @(#)AlignToolBar.java  1.2  2008-05-23
 *
 * Copyright (c) 2007-2008 by the original authors of JHotDraw
 * and all its contributors.
 * All rights reserved.
 *
 * The copyright of this software is owned by the authors and  
 * contributors of the JHotDraw project ("the copyright holders").  
 * You may not use, copy or modify this software, except in  
 * accordance with the license agreement you entered into with  
 * the copyright holders. For details see accompanying license terms. 
 */
package org.jhotdraw.samples.svg.gui;

import dk.sdu.mmmi.featuretracer.lib.FeatureEntryPoint;
import javax.swing.border.*;
import org.jhotdraw.util.*;

import java.awt.*;
import javax.swing.*;
import org.jhotdraw.app.JHotDrawFeatures;
import org.jhotdraw.draw.*;
import org.jhotdraw.draw.action.*;
import org.jhotdraw.gui.plaf.palette.*;

/**
 * AlignToolBar.
 *
 * @author Werner Randelshofer
 * @version 1.2 2008-05-23 Hide the toolbar if nothing is selected, and no
 * creation tool is active.
 * <br>1.1 2008-03-26 Don't draw button borders.
 * <br>1.0 May 1, 2007 Created.
 */
public class AlignToolBar extends AbstractToolBar {

    private SelectionComponentDisplayer displayer;
    private ResourceBundleUtil labels;
    protected JPanel panel = new JPanel();

    /**
     * Creates new instance.
     */
    public AlignToolBar() {
        this.labels = ResourceBundleUtil.getBundle("org.jhotdraw.samples.svg.Labels");
        setName(labels.getString(getID() + ".toolbar"));
    }

    @Override
    public void setEditor(DrawingEditor newValue) {
        DrawingEditor oldValue = getEditor();
        if (displayer != null) {
            displayer.dispose();
            displayer = null;
        }
        super.setEditor(newValue);
        if (newValue != null) {
            displayer = new SelectionComponentDisplayer(editor, this);
            displayer.setMinSelectionCount(2);
            displayer.setVisibleIfCreationTool(false);
        }
    }

    protected void createButton(AbstractButton button) {
        button.setUI((PaletteButtonUI) PaletteButtonUI.createUI(button));
        button.putClientProperty("hideActionText", Boolean.TRUE);
        button.setText(null);
    }

    protected void createBorder() {
        panel.setBorder(new EmptyBorder(5, 5, 5, 8));
    }

    protected void createEastButton(JPanel p, GridBagConstraints gbc) {

        AbstractButton btn;

        gbc.insets = new Insets(0, 3, 0, 0);
        btn = new JButton(new AlignAction.East(editor, labels));
        createButton(btn);
        p.add(btn, gbc);
    }

    protected void createWestButton(JPanel p, GridBagConstraints gbc) {
        AbstractButton btn;

        gbc.gridy = 0;
        gbc.insets = new Insets(0, 3, 0, 0);
        btn = new JButton(new AlignAction.West(editor, labels));
        createButton(btn);
        p.add(btn, gbc);
    }

    protected void createNorthButton(JPanel p, GridBagConstraints gbc) {
        AbstractButton btn;

        gbc.gridy = 1;
        gbc.insets = new Insets(3, 0, 0, 0);
        btn = new JButton(new AlignAction.North(editor, labels));
        createButton(btn);
        p.add(btn, gbc);
    }

    protected void createSouthButton(JPanel p, GridBagConstraints gbc) {
        AbstractButton btn;

        gbc.insets = new Insets(3, 3, 0, 0);
        btn = new JButton(new AlignAction.South(editor, labels));
        createButton(btn);
        p.add(btn, gbc);
    }

    protected void createHorizontalButton(JPanel p, GridBagConstraints gbc) {
        AbstractButton btn;

        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.insets = new Insets(3, 0, 0, 0);
        btn = new JButton(new AlignAction.Horizontal(editor, labels));
        createButton(btn);
        p.add(btn, gbc);
    }

    protected void createVerticalButton(JPanel p, GridBagConstraints gbc) {
        AbstractButton btn;

        gbc.gridx = 1;
        gbc.insets = new Insets(3, 3, 0, 0);
        btn = new JButton(new AlignAction.Vertical(editor, labels));
        createButton(btn);
        p.add(btn, gbc);
    }

    @Override
    @FeatureEntryPoint(JHotDrawFeatures.ALIGN_PALETTE)
    protected JComponent createDisclosedComponent(int state) {
        createBorder();
        GridBagLayout layout = new GridBagLayout();
        panel.setLayout(layout);
        panel.setOpaque(false);

        GridBagConstraints gbc = new GridBagConstraints();
        

        createWestButton(panel, gbc);
        createEastButton(panel, gbc);
        createNorthButton(panel, gbc);
        createSouthButton(panel, gbc);
        createHorizontalButton(panel, gbc);
        createVerticalButton(panel, gbc);
        return panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected String getID() {
        return "align";
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
